#    _
#   |_) _ _  _ _|_. _ _					  	Copyright (C) 2022
#   |  | (_|(_  | |(_(_) 				  	John F. Arroyave Gutiérrez
#     www.practico.org					  	unix4you2@gmail.com
#                                           All rights reserved.
#   
#	This program is free software; you can redistribute it and/or
#	modify it under the terms of the GNU General Public License
#	as published by the Free Software Foundation; either version 2
#	of the License, or (at your option) any later version.

#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.

#	You should have received a copy of the GNU General Public License
#	along with this program; if not, write to the Free Software
#	Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

#   Configuraciones de aplicacion para Google App Engine
#   Referencia: https://cloud.google.com/appengine/docs/standard/python/config/appref


##############
#  STANDARD  #
##############
#runtime: php72  # php72|php73
#env: standard
##api_version: 1 # Obsoleto GAE version 7.2 PHP no requiere API Version


##############
#  FLEXIBLE  #
##############
runtime: php    # Reemplazar con php( para flex) o php72 y php73 (para estandar)
env: flex       # flex|flexible=Sistema de archivos RW 
runtime_config:
  document_root: public  # Raiz del servidor web
  skip_lockdown_document_root: true
  front_controller_file: index.php

#################################
#    DEFINICION DEL SERVICIO    #
#################################
service: practico-framework

handlers:
# Publica un directorio como contenido estatico
- url: /inc/bootstrap/css
  static_dir: inc/bootstrap/css

# Sirve todas las imagenes como recursos estaticos
- url: /(.+\.(gif|png|jpg|ico))$
  static_files: \1
  upload: .+\.(gif|png|jpg|ico)$

# Sirve otras extensiones como estaticas
- url: /(.+\.(js|css|less|scss|svg|eot|ttf|woff|woff2|otf|json|xml|htm|html|txt))$
  static_files: \1
  upload: .+\.(js|css|less|scss|svg|eot|ttf|woff|woff2|otf|json|xml|htm|html|txt)$

# Sirve la aplicacion en general como index.php o public/index.php.
- url: .*
  script: auto  # Antes: index.php

# Para evitar el despliegue de archivos y directorios especificos (ver archivo .gcloudignore)

#beta_settings:
  # for Cloud SQL, set this value to the Cloud SQL connection name,
  # e.g. "project:region:cloudsql-instance"
  # cloud_sql_instances: "YOUR_INSTANCE_NAME"