name: "CodeQL_PCO_Fmk"

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#  schedule:
#    - cron: '42 14 * * 0'
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  Trabajo01:
    name: Pruebas Generales
    runs-on: ubuntu-latest

    steps:
    - name: PRE-Pruebas - Instalando BaseOS+DEVTools
      shell: bash
      run: sudo apt-get -y update; sudo apt-get -y upgrade; sudo apt-get -y install git

    - name: PRE-Pruebas - Activacion servicios basicos
      shell: bash
      run: sudo systemctl stop mono-xsp4; sudo systemctl start apache2; sudo systemctl status apache2; sudo systemctl start mysql.service

    - name: PRE-Pruebas - Revision de versiones
      shell: bash
      run: php -v; git --version

    - name: PRE-Pruebas - Clonacion Repositorio
      shell: bash
      working-directory: /var/www/html
      env:
         Vble: MiVBLE
      run: sudo rm -rf *; sudo git clone https://github.com/unix4you2/practico.git; sudo chmod -R 777 *; cp /var/www/html/practico/dev/test/t_conf.php /var/www/html/practico/configuracion.php



    - name: PRE-Pruebas - Impresion exploratoria
      shell: bash
      run: sudo ls /var/www/html/practico/; pwd; cat /var/www/html/practico/configuracion.php



    # Initializes the CodeQL tools for scanning.
#    - name: Initialize CodeQL
#      uses: github/codeql-action/init@v2
#      with:
#        languages: ${{ matrix.language }}
        # If you wish to specify custom queries, you can do so here or in a config file.
        # By default, queries listed here will override any specified in a config file.
        # Prefix the list here with "+" to use these queries and those in the config file.
        
        # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
        # queries: security-extended,security-and-quality

        
    # Autobuild attempts to build any compiled languages  (C/C++, C#, or Java).
    # If this step fails, then you should remove it and run the build manually (see below)
#    - name: Autobuild
#      uses: github/codeql-action/autobuild@v2

    # ℹ️ Command-line programs to run using the OS shell.
    # 📚 See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun

    #   If the Autobuild fails above, remove it and uncomment the following three lines. 
    #   modify them (or add more) to build your code if your project, please refer to the EXAMPLE below for guidance.

    # - run: |
    #   echo "Run, Build Application using script"
    #   ./location_of_script_within_repo/buildscript.sh

#    - name: Perform CodeQL Analysis
#      uses: github/codeql-action/analyze@v2
#      with:
#        category: "/language:${{matrix.language}}"


#https://docs.github.com/es/actions/using-workflows/workflow-syntax-for-github-actions
#https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md